services:
  db:
    image: postgres:18
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - db_data:/var/lib/postgresql
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 5
  dev:
    build:
      context: .
      target: dev
    volumes:
      - ${PWD}:${PWD}
    working_dir: ${PWD}
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://postgres@db:5432/postgres?sslmode=disable
    cap_drop:
      - ALL
    command: sleep infinity

  pgweb:
    image: sosedoff/pgweb
    ports:
      - "127.0.0.1:8081:8081"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PGWEB_DATABASE_URL=postgres://postgres@db:5432/postgres?sslmode=disable
    cap_drop:
      - ALL

volumes:
  db_data:
